# Generated by Django 3.2.7 on 2021-09-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0003_auto_20210919_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='familyhistory',
            field=models.TextField(),
        ),
    ]
