# Generated by Django 3.2.7 on 2021-09-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0006_alter_patients_smoking'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madeon', models.DateField()),
                ('drname', models.CharField(max_length=200)),
                ('aptdatetime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='email',
        ),
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom', models.TextField(max_length=200)),
                ('condition', models.TextField(max_length=200)),
                ('notes', models.TextField(max_length=500)),
                ('followupbool', models.BooleanField(default=False)),
                ('appointmentno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.appointments')),
            ],
        ),
        migrations.CreateModel(
            name='recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoURL', models.URLField()),
                ('messageURL', models.URLField()),
                ('visitno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.visits')),
            ],
        ),
        migrations.CreateModel(
            name='prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.TextField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('patientno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patients')),
            ],
        ),
        migrations.CreateModel(
            name='medicationsallergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.TextField(max_length=200)),
                ('enddatemedications', models.DateField()),
                ('allergies', models.TextField(max_length=200)),
                ('patientno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patients')),
            ],
        ),
        migrations.CreateModel(
            name='immunizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunizations', models.TextField(max_length=200)),
                ('dateimmunization', models.DateField()),
                ('patientno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patients')),
            ],
        ),
        migrations.CreateModel(
            name='chartreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('notes', models.TextField(max_length=250)),
                ('fileurl', models.URLField()),
                ('date', models.DateField()),
                ('patientno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patients')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='patientno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemedicine.patients'),
        ),
    ]
