# Generated by Django 3.2.7 on 2021-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0007_auto_20210928_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ethnicity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='familyhistory',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patients',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
