# Generated by Django 3.2.7 on 2021-09-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0010_alter_patients_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='smoking',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
